### ISSUE TITLE
publish container images to dockerhub

### ISSUE THREAD

**Issue by seriousme** [openwhisk/openwhisk#171] opened 2016-04-04 18:57 UTC
Hi,

I managed to get openwhisk running using vagrant. After some fiddling I got the examples to work.
This made me wonder: if the openwhisk specific containers were available on docker hub it would be much easier to give it a spin (e.g. [docker-compose](https://docs.docker.com/compose/) up would be enough).
It would have also saved me a truckload of downloads :-)

I also noticed that the images are fairly large, e.g.
-  a simple node.js container can be had for about [13 MB](https://hub.docker.com/r/mhart/alpine-node/tags/) instead of the current 400+ MB
- Consul can be had for [18 Mb](https://hub.docker.com/r/gliderlabs/consul/tags/) instead of the current 1347 MB
  etc.

I know that images share layers, but still smaller images are easier to juggle around ;-)

Cheers,
Hans

**Comment by domdom82** [comment] 2016-04-05 07:56
Hi @seriousme thanks for your excellent input.

I think it is a great idea to have the stack as compose topology on dockerhub. 

Before we do that we should first reduce the image sizes so ppl won't have to download huge chunks.

Most images are based on whisk/scala which itself is pretty large. That itself can be reduced imho.

As for the consul part, we are currently working on moving to ansible for our deployment. During that process we are also looking into ways to reduce overhead on common tools such as consul which we currently build ourselves. So chances are we got rid of that image soon.

**Comment by seriousme** [comment] 2016-04-05 17:19
@domdom82 Thanks for the positive feedback :-)

I found a relatively small scala package [frolvlad](https://hub.docker.com/r/frolvlad/alpine-scala/) based on Alpine Linux. Now I'm not a Scala expert, so I might be way off here, but alpine-scala is build on alpine-java (oracle jdk) which in turn is build on Alpine.  

However if you want to stay main stream there is also a [docker java base image](https://hub.docker.com/_/java/) which might be used as a starter to a Scala image.

Ideally there would imho be a few docker compose files: 
- one that uses cloudant as its DB
- one that uses a couchdb container as its DB (preferably with a separate data volume)

I noticed my repository on the VM also contains a CLI container, I would include that as well in the compose files.

Last point: the couchdb container is the only one started without a predefined name in [start-couchdb-box.sh] (https://github.com/openwhisk/openwhisk/blob/master/tools/db/couchdb/start-couchdb-box.sh#L30), adding a --name parameter would make it easier to reference it, and it just looks more clean as all the other containers have nice names :-)

Cheers,
Hans

**Comment by markusthoemmes** [comment] 2016-09-25 22:09
I've iterated on this a couple of times. Anything actionable that we want to keep from the issue? @domdom82 ?

**Comment by skaegi** [comment] 2016-10-06 05:24
I'm also interested in this. Does anyone have a docker-compose file in a repo some where that I might start from?

**Comment by ddragosd** [comment] 2017-01-10 00:45
In the meanwhile `docker-compose` support has arrived here: https://github.com/openwhisk/openwhisk-devtools/tree/master/docker-compose . Currently it downloads the code, it compiles it, and it starts an instance of OpenWhisk locally.

**Comment by seriousme** [comment] 2017-01-10 17:51
Is there anything site specific in those freshly built containers ?
If not, it would be way more convenient to have the containers uploaded to docker hub and just provide a docker-compose file.
Saves a lot of people the hassle (and CPU cycles) of building openwhisk and the containers.

**Comment by ddragosd** [comment] 2017-01-11 00:12
> it would be way more convenient to have the containers uploaded to docker hub

👍 @seriousme . Actually `docker-compose.yaml` is ready for that; there's no build instruction. Once the images are available in Docker Hub we'll skip the build step in the Makefile, leaving it optionally. There's already a separate `make docker` command in the Makefile that does the build.

At the same time, here's something interesting:

```bash
> docker images | grep "whisk/invoker\|whisk/controller\|whisk/nodejs6action\|zoo\|kafka\|openwhisk/apigateway\|consul\|registrator\|redis" | awk '{s+=$7} END {print s " MB"}'
2655.57 MB
```

**Comment by rabbah** [comment] 2017-01-11 00:30
The runtime containers are already on dockerhub fwiw.

**Comment by seriousme** [comment] 2017-01-12 20:40
Ehm, `docker images` looks at your local image cache and not at docker hub AFAIK.

`docker search whisk` list a whole slew of images with the name whisk in there but no whisk/invoker nor whisk/controller and the whisk/kafka is over a year old (which might be prefectly ok, but I cant tell as the repo description is empty.

Is "whisk" the official open whisk docker repo on docker hub ? I guess not, since the profile points to https://whisk.com/

There is also an openwhisk docker repo (https://hub.docker.com/u/openwhisk/) which seems to be an (the ?) official openwhisk repo, but the profile is rather empty.

It would be nice if the quickstart page ( https://github.com/openwhisk/openwhisk#quick-start) would mention the openwhisk/* containers and ideally point to the compose file so people can skip the whole compilation if they just want to try it out.

**Comment by rabbah** [comment] 2017-01-12 20:50
`https://hub.docker.com/u/openwhisk` is it. @csantanapr we should populate the profile.
Locally images are tagged as `whisk` - this can be changed via a gradle parameter @markusthoemmes please advise.

**Comment by markusthoemmes** [comment] 2017-01-13 09:56
Advisory on its way:

To be able to push to `openwhisk` we'll need to tag the images accordingly. [`gradle distDocker -PdockerImagePrefix=openwhisk`](https://github.com/openwhisk/openwhisk/blob/master/gradle/docker.gradle#L27) should do the trick there.

**Comment by csantanapr** [comment] 2017-03-10 15:03
>https://hub.docker.com/u/openwhisk is it. @csantanapr we should populate the profile.

@rabbah done
![image](https://cloud.githubusercontent.com/assets/1094878/23800050/c6a0c54e-0578-11e7-9daa-3efdff8bddbb.png)

**Comment by rabbah** [comment] 2017-03-10 15:16
Profile updated yes. But we need to automate the image push or build for our containers.

**Comment by seriousme** [comment] 2017-03-10 16:10
Looking at the [compose file](https://github.com/openwhisk/openwhisk-devtools/blob/master/docker-compose/docker-compose.yml) from the sidelines I notice the following:

The images are required to get a working service are:
 - image: couchdb:1.6
 - image: wurstmeister/zookeeper
 - image: wurstmeister/kafka
 - image: consul:v0.7.0
 - image: gliderlabs/registrator
 - image: whisk/controller:latest
 - image: whisk/invoker:latest
 - image: redis:2.8
 - image: adobeapiplatform/apigateway:1.1.0

I presume `whisk` would then be replaced by `openwhisk` however the [openwhisk docker repository](https://hub.docker.com/u/openwhisk)  holds no `invoker` nor 'controller` image.
It does however hold 2 api-gateway images (??) which are not referenced in the compose file.

Its also a bit remarkable that the setup uses both Zookeeper and Consul, but also both Kakfa and Redis. I can see how it got there (e.g. Kafka needs Zookeeper) but from a distance it looks like the setup can be optimized a bit and the repo can be cleaned up a bit ;-)

**Comment by csantanapr** [comment] 2017-03-10 16:43
>Profile updated yes. But we need to automate the image push or build for our containers.

@rabbah I was just asking if when you said "profile" you were referring only to the the picture

**Comment by csantanapr** [comment] 2017-03-10 16:44
@rabbah I see we have automated builds already for the runtimes.

Why we can't setup invoker and controller in the same way?

**Comment by csantanapr** [comment] 2017-03-10 16:54
@seriousme 
>It does however hold 2 api-gateway images (??) which are not referenced in the compose file.

I clean up one of them there should be only one now `openwhisk/apigateway`

And docker compose file should be updated to use it https://github.com/openwhisk/openwhisk-devtools/issues/2

**Comment by csantanapr** [comment] 2017-03-10 16:57
@seriousme
>Its also a bit remarkable that the setup uses both Zookeeper and Consul, but also both Kakfa and Redis. 

Redis it's only use by nginx/lua [apigateway](https://github.com/openwhisk/openwhisk-apigateway), this is by design. You can ask questions about Redis usage on that repo, as the SMEs are actively working on the repo and looking at open issues.

**Comment by rabbah** [comment] 2017-03-10 17:12
The runtime builds are not automated - I occasionally click the build now button. That's of course not a long term answer. Either automated builds (pull model) or travis does the publishing (push model). I think all our components should have images on docker hub, that's the point of this issue, isn't it?

**Comment by markusthoemmes** [comment] 2017-03-10 17:12
@csantanapr Invoker and Controller currently cannot be build automatically because we compile outside of the container. We can certainly change that but there might be sideeffects to consider.

**Comment by csantanapr** [comment] 2017-03-10 17:16
>The runtime builds are not automated - I occasionally click the build now button. 
Why? I configured other images for pulling, I will enable automatic pulling then if there are no objections for the runtimes.

**Comment by csantanapr** [comment] 2017-03-10 17:18
@rabbah I see errors in automatic builds for example `openwhisk/pythonaction`

Build failed: Error: image library/dockerskeleton:latest not found

Here https://hub.docker.com/r/openwhisk/pythonaction/builds/

It tried to build an hour ago

**Comment by csantanapr** [comment] 2017-03-10 17:21
@markusthoemmes Would doing the compile with the docker build would have less side effects? then when the image is build/done the code is compiled and the image done, no window for errors if trying to compile in a different environment that can introduce side effects.

**Comment by rabbah** [comment] 2017-03-10 17:22
Isn't the easiest path through this to have travis do a travis push/tag at the end of a build from master?

**Comment by csantanapr** [comment] 2017-03-10 22:36
Yes let's configure Travis do it. I heard that open source projects from Netflix do the same because they got same problems of custom steps that docker hub  build service doesn't handle.

**Comment by rabbah** [comment] 2017-03-14 19:30
@csantanapr is this a duplicate of #2017 now?

**Comment by csantanapr** [comment] 2017-03-15 00:08
Let's close new one and keep this old one

**Comment by csantanapr** [comment] 2017-03-15 00:09
It should be possible to configure Travis to push the docker images for controller, invoker, and runtimes to dockerhub openwhisk.

The push should happen only from master branch, and using Travis credentials to store the dockerhub credentials.

The only thing to be careful is not going over the 50 max time for a travis build.

**Comment by seriousme** [comment] 2017-03-15 10:26
A description of the process of building Docker images using Travis can be found at https://sebest.github.io/post/using-travis-ci-to-build-docker-images/

**Closed** 2017-04-03 22:07 UTC
Labels: deployment, docker, enhancement
