### ISSUE TITLE
In Swagger file, payload described as KeyValue model does not correspond to what server is expecting

### ISSUE THREAD

**Issue by fabdslv** [openwhisk/openwhisk#401] opened 2016-05-12 14:10 UTC
KeyValue defines an object as-is : ```{'key': 'name', 'value':'Phil'}``` while server only accepts ```{'name':'Phil'}```.

**Comment by paulcastro** [comment] 2016-05-21 18:34
Just a clarification, this is for action POST.

**Comment by rabbah** [comment] 2016-05-24 14:25
confirmed - related to #270.

**Comment by rabbah** [comment] 2016-07-31 15:17
Closing as duplicate of 270.

**Closed by rabbah** 2016-07-31 15:17 UTC
Labels: API, swagger
