### ISSUE TITLE
Not all samples are getting installed

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#302] opened 2016-05-02 20:39 UTC
@starpit brought up that not all samples are getting installed from the [catalog/installSystem.sh](https://github.com/openwhisk/openwhisk/blob/master/catalog/installSystem.sh)

The following samples are not getting installed:
countdown.js (improve) see https://github.com/openwhisk/openwhisk/issues/302#issuecomment-216588113 for more details
curl.js (rename and improve) see https://github.com/openwhisk/openwhisk/issues/302#issuecomment-216588113 for more details
hello.swift (implement tests and deploy) see https://github.com/openwhisk/openwhisk/issues/302#issuecomment-216588113 for more details
delete -> helloAsync.js
delete -> printParams.js
delete -> wcbin.js

**Comment by sjfink** [comment] 2016-05-02 20:45
couple of thoughts:
- all samples which are installed by default should have adequate tests.
- we probably don't need all of these.   Some (helloAsync, printParams, wcbin?) can probably be deleted instead.

**Comment by rabbah** [comment] 2016-05-02 20:46
`wcbin` is poorly named - it's an example of an action calling another action using a blocking invoke.
`countdown` shouldn't be in the catalog as is because is it not parametric to the namespace (see https://github.com/openwhisk/openwhisk/issues/80#issuecomment-206634585).

**Comment by markusthoemmes** [comment] 2016-05-02 21:55
Do we want to keep `curl.js`?

**Comment by rabbah** [comment] 2016-05-02 22:03
as an example of calling a "process"? But could use a better example than curl.

**Comment by starpit** [comment] 2016-05-02 22:08
one of the drivers for this is that the UI will now show the samples list front and center. so having a compelling list will become important pretty soon.

to me, "compelling" means:

1) high orthogonality; we have several very similar actions
2) super easy to use; no mystery API key
3) at least two languages?
4) at least some have to be not simple utility routines

Hello World in Javascript
Hello World in Swift
Weather Forecast
Programmatic API: Calling a non-OpenWhisk API
Sequencing: Integrating an OpenWhisk API
Rules: Periodic Weather Forecast

**Comment by csantanapr** [comment] 2016-05-03 16:38
It looks like we need to do some clean up

- keep hello.js (Hello World in Javascript)

- keep hello.swift (Hello World in Swift) and installed it and add testing, this is related to #188 that @bjustin-ibm is looking into

- create new sample for js only (i.e. no swift) for weather forecast using yahoo plubic api that doesn't require api key same code as in the docs here https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md#using-actions-to-call-an-external-api. This ones is to show how to call an external API in the docs currently

- delete helloAsync.js 

- delete printParams.js

- delete wcbin.js

- rename curl.js (Shows how to use whisk.aysnc and whisk.done) Currently calls background process, according to @rabbah https://github.com/openwhisk/openwhisk/issues/302#issuecomment-216378984 we need to use a better process than curl in. maybe sleep?. Only js (i.e. no swift) 

- countdown.js (Show how to use whisk.invoke() from inside an action) improve with new implementation from @rabbah https://github.com/openwhisk/openwhisk/issues/80#issuecomment-206634585. Add testing for it. Only for js (i.e. no swift) 

@starpit let's have a chat on the following 3
- Programmatic API: Calling a non-OpenWhisk API
(Does the action calling yahoo weather api covers, or you mean something else?)

- Sequencing: Integrating an OpenWhisk API
It looks like there are two concepts here. you want a sample with action sequence for example 2 actions, action 1 output is the input to action 2?
Or an action that programmatically creates two actions, and  a sequence with those actions using the whisk client sdk inside a nodejs action?

- Rules: Periodic Weather Forecast
It looks like there are two concepts here. you want to show the concept of a rule using alarm and yahoo weather, we need to be careful as not hitting the rate limit on the yahoo weather public api with no api key. It would be kind of tricky to get a simple sample to work out of the box.
Maybe we can show an action that shows how to use whisk.trigger() and there is a rule that comes in samples to listen to the trigger and invokes the forecast.

**Comment by rabbah** [comment] 2016-07-31 15:28
@csantanapr @mrutkows @houshengbo Is this a duplicate of other catalog related migration issues?

**Comment by csantanapr** [comment] 2016-08-01 19:47
@rabbah I think this clean up should be done as part of the migration and refactoring of openwhisk-catalog repo.

**Comment by mrutkows** [comment] 2016-08-02 22:00
@rabbah indeed the plan includes not moving any unused actions or those jointly agreed-upon as not being useful from a functional, testing or teaching perspective.

**Comment by rabbah** [comment] 2017-01-24 04:05
solved by openwhisk-catalog cleanup.

**Closed by rabbah** 2017-01-24 04:05 UTC
Labels: packages
