### ISSUE TITLE
upgrade to ansible latest version

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#967] opened 2016-07-28 21:14 UTC
## Steps to reproduce the issue:

For each PR submitted to openwhisk, the travis ci will running into a issue that db_local.ini is missing.

## Additional information you deem important:
* we can specify the ansible version to 2.0.2.0 to make sure everything works smooth.

**Comment by rabbah** [comment] 2016-07-29 03:40
@lehoanganh can we upgrade required ansible to at least v2.1.0.0? the latest release might fix #632 but requires other changes to our playbooks.

**Comment by lehoanganh** [comment] 2016-07-29 11:45
I'm trying the latest version. The drawback of pinned version with apt-get is, the Ansible team delete the old version once they publish the new version in the repo. We were also facing this problem in the past where the pinned version was not found via apt-get.

**Comment by rabbah** [comment] 2016-07-29 11:51
so the pip path while results in a longer install step might be best in general?

**Comment by lehoanganh** [comment] 2016-07-29 11:53
or we can pin the version, if the problem occurs again, fix it with the new version. With such process, we can control the installed version.

**Comment by lehoanganh** [comment] 2016-07-29 11:55
An example for you
https://travis-ci.org/lehoanganh/openwhisk/builds/148289322

Try this pull: https://github.com/openwhisk/openwhisk/pull/968/files

```
E: Version '2.1.0.0-1*' for 'ansible' was not found
```

```
lha@ubuntu  ~  sudo apt-cache policy ansible
ansible:
  Installed: (none)
  Candidate: 2.1.1.0-1ppa~trusty
  Version table:
     2.1.1.0-1ppa~trusty 0
        500 http://ppa.launchpad.net/ansible/ansible/ubuntu/ trusty/main amd64 Packages
     1.7.2+dfsg-1~ubuntu14.04.1 0
        100 http://us.archive.ubuntu.com/ubuntu/ trusty-backports/universe amd64 Packages
     1.5.4+dfsg-1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

`2.1.0.0-1` was deleted from repo

**Comment by rabbah** [comment] 2016-07-29 12:02
so pip install 2.0.0.2 or 2.1.0.0?

**Comment by lehoanganh** [comment] 2016-07-29 12:15
`pip install --user ansible==2.0.2.0` worked. https://travis-ci.org/lehoanganh/openwhisk/builds/148293667

**Comment by lehoanganh** [comment] 2016-07-29 12:17
pip persists all versions of a package

```
lha@dyn-9-152-96-140  ~/Development/hoang/openwhisk   test-travis  pip install ansible==1111111111111
Collecting ansible==1111111111111
  Could not find a version that satisfies the requirement ansible==1111111111111 (from versions: 1.0, 1.1, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0.1, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 2.0.0.0, 2.0.0.1, 2.0.0.2, 2.0.1.0, 2.0.2.0, 2.1.0.0, 2.1.1.0)
```

**Comment by lehoanganh** [comment] 2016-07-29 12:28
`2.1.1.0-1` (latest) didn't work, maybe syntax changes in `setup.yml` which does not like other ansible version greater than 2.0.2.0.

**Comment by rabbah** [comment] 2016-07-29 13:06
Travis restored by pinning to earlier version. Leaving this issue open to address upgrade to latest ansible. Also going to close #632 as duplicate of this since latest ansible contains the fix for spaces in path.

**Comment by csantanapr** [comment] 2016-08-05 14:01
Needs investigation, to see if it's a bug in ansible or a bug in ourside on how we use the latest ansible.

**Closed** 2016-08-30 19:57 UTC
Labels: ansible
