### ISSUE TITLE
Namespace in "activation list" command is actually name of the action

### ISSUE THREAD

**Issue by archerzz** [openwhisk/openwhisk#1344] opened 2016-09-29 12:28 UTC
## Environment details:

ALL
## Steps to reproduce the issue:
1.   Execute "wsk activation list NAMESPACE -v"
2.   You will find that the request URL path is like "/api/v1/namespaces/_/activations?limit=30&name=NAMESPACE&skip=0"
3. And the returned activation list is those which belong to action of which the name is "NAMESPACE", not those under specific NAMESPACE.
## Provide the expected results and outputs:

```
 I think the correct one should be "/api/v1/namespaces/NAMESPACE/activations?limit=30&skip=0"
```
## Provide the actual results and outputs:

```
the request URL path is like "/api/v1/namespaces/_/activations?limit=30&name=NAMESPACE&skip=0"
```

**Comment by rabbah** [comment] 2016-09-29 18:28
This is a know bug/feature and is working as intended. The underlying reason is that in openwhisk there isn't yet a mechanism to create more than one namespace per subject but in other deployments that provide IAM, it is possible to to have more than one subject per namespace. In this case, activations require a way to disambiguate the namespace to hold the activation which is not possible with one subject key mapping to more than one namespace.

As a result, all activations are stored in one namespace. The CLI ignores the namespace so that one can see all their activations. Before we fix the CLI, we need to resolve other blocking issues under #1107.

**Comment by rabbah** [comment] 2017-01-11 23:25
@markusthoemmes I think we've resolved this already despite 1107 still being open (the enabler is already merged). Confirm/close?

**Comment by markusthoemmes** [comment] 2017-01-12 09:31
Although the enabler is merged, i'd like to have #1681 merged before closing for it to be fully implemented throughout the codebase.

**Comment by dubeejw** [comment] 2017-02-07 21:33
@csantanapr, sounds like this can be closed.

**Comment by csantanapr** [comment] 2017-02-07 21:41
@dubeejw 👍

**Closed by csantanapr** 2017-02-07 21:41 UTC
Labels: blocked, bug, cli
