### ISSUE TITLE
Sanitize packages recursively

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#1588] opened 2016-12-05 13:18 UTC
In some of our tests we create packages that include actions. If that fails for some reason, the test cannot be run again, because `sanitize` fails to delete the package properly.

We should fix this by having a recursive sanitize *before* the test.

**Comment by rabbah** [comment] 2017-02-24 22:51
closing as duplicate of issue linked above.

**Closed by rabbah** 2017-02-24 22:51 UTC
Labels: testing
