### ISSUE TITLE
Japanese Character Mojibake

### ISSUE THREAD

**Issue by kaya-mikio** [openwhisk/openwhisk#1737] opened 2017-01-19 06:21 UTC
## Environment details:

* We just encountered Japanese Character mojibake in openwhisk action's output
* node.js on Bluemix

## Steps to reproduce the issue:

1.   simply output Japanese character

## Provide the expected results and outputs:

```
日本語文字化け
```

## Provide the actual results and outputs:

```
???????
```

## Additional information you deem important:
* Is it OK to use ja_JA in i18n.go? We use ja_JP instead of ja_JA usually.

**Comment by rabbah** [comment] 2017-01-19 23:04
I suspect this is a duplicate of https://github.com/openwhisk/openwhisk/issues/252.
base64 encoding the response is one work around.

**Comment by rabbah** [comment] 2017-01-24 22:47
Closing as duplicate. Confirmed nodejs bug.

**Closed by rabbah** 2017-01-24 22:47 UTC
