### ISSUE TITLE
An API is only as good as its documentation (swagger)

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#597] opened 2016-06-08 16:11 UTC
We are currently using swagger to document the OpenWhisk API.

The [whiskswagger.json](https://github.com/openwhisk/openwhisk/blob/master/core/controller/src/resources/whiskswagger.json) is not accurate matching the implementation of the OpenWhisk API.

You can view OpenWhisk API docs in [Swagger UI](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/openwhisk/openwhisk/master/core/controller/src/resources/whiskswagger.json)

There are several issue reports of people finding this inconsistencies

This Epic is to capture all work items to get swagger docs stable and 100% accurate.

We currently have some tests here https://github.com/openwhisk/openwhisk/blob/9e87bbfc0e9326aa13ab233400b4b860fa97d34a/tests/src/system/rest/SwaggerTests.scala

We should reach a point that no PR is merged containing API changes if doesn't 
accompanied by swagger related changes.

Something for inspiration :-) https://rocketeer.be/blog/2015/03/api-quality/

**Comment by sjfink** [comment] 2016-06-08 16:30
We have a few regression tests that check that the swagger matches the behavior.   We probably need many more such tests.

**Comment by rabbah** [comment] 2016-06-08 16:58
duplicate/related to #270.

**Comment by csantanapr** [comment] 2016-06-08 17:11
@sjfink That's one of the main work items, to add many many tests
@rabbah Close this one and convert #270 in to an Epic?

**Comment by rabbah** [comment] 2017-03-10 13:54
closing as duplicate of 270 - will make that into an epic.

**Closed by rabbah** 2017-03-10 13:54 UTC
Labels: Epic, swagger
