### ISSUE TITLE
feature request: "catch", needed for 401/403 handling in web-exported actions

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#1793] opened 2017-02-01 15:53 UTC
Say I have a web-exported sequence `S: A=>B=>C` and action `B` is responsible for some kind of authentication or authorization. Thus, `B` may encounter a 403 or 401 situation, and, if so, needs to short-circuit the execution of the sequence.

Unfortunately, short-circuiting of sequences can only be done by `reject()`'ing in action `B`. Today, this results in the web-exporter communicating a 400 to the client: no opportunity for clearing server-side session cookies, or redirecting the client to a login page.

More broadly, I suggest that `B` should not know about web-export. It *should* simply reject the request. It is the entire sequence `S` that has been exported, so the notion of web-oriented error handling should be encapsulated at the level of `S`, not `B`.

We could accomplish this by supporting a `catch` operator. For example: 
```
wsk package bind Http BluemixHttp -p redirect_uri https://bluemix.net/login
wsk action update S A,B,C --annotation catch BluemixHttp/403
```

i.e. when the sequence short-circuits, invoke the action `Http/403`. Here, we have the opportunity to provide a general package `Http` that implements common catch patterns.

**Comment by starpit** [comment] 2017-02-01 15:56
an open question here is at what level is the error code matching done? within the catch action? or by the controller? there is something attractive about having separate 403, 500, etc. catch handler actions.

**Comment by markusthoemmes** [comment] 2017-02-01 15:58
Alternative proposal: The Controller tries to evaluate an `error` response as well, much like we do for actual responses today, to alter the statusCode returned?

**Comment by starpit** [comment] 2017-02-01 16:00
it's still the case that there is custom logic that needs to be invoked. e.g. which cookies to clear? where to redirect the user?

i agree that ew can either put the "match" in the controller on in the catch action. but, in either case, some custom logic needs to be invoked?

**Comment by rabbah** [comment] 2017-02-01 16:03
> The Controller tries to evaluate an error response as well, much like we do for actual responses today, to alter the statusCode returned?

That will break separation of concerns - web extensions should not permeate actions which are not web-exported and hence do not understand the extensions.

**Comment by sjfink** [comment] 2017-02-01 21:45
alternative proposal:

high-level sketch here, low-level details to be discussed.

We create a built-in system feed in the whisk.system package, called 'exception'.   Define the set of abnormal exit conditions to be, for example, E := { 'error', 'abort' }.     You can instantiate the exception feed for action A and exit condition C, which causes the system feed to fire a trigger when A exits with condition C.

So to install an exception handler the user creates a rule to handle the exception feed.

Note that this solution is a fire-and-forget asynchronous approach to exception handling.     It does not allow action composition with exception handlers in composed actions, so is weaker than scoped exception handing in a language.    However, this proposal seems like a less ambitious, less disruptive change to the programming model. as compared to a new construct for scoped exception handling with composition.

**Comment by mbehrendt** [comment] 2017-02-02 09:05
I think we also need to look at the ease of use / dev experience here:

if B does some auth work and should be able to return a 401 or a 403 (or sth else), it would be most straightforward to me as a dev if i could just return a 403/401 or whatever from B -- so I like @markusthoemmes . When I'm writing B I *know* that this can result in a 401/403, so why not let devs just code it in there?

Having to add that information to be metadata of the action makes my life as a dev more cumbersome, I have to code the action * change the metadata.

**Comment by rabbah** [comment] 2017-02-02 10:50
You're focusing on the narrow case - the more general programming model question is to allow a allow for try/catch (or scala terms recover with). In Steve's latter proposal, he also describes what could be the start of allowing developers to create handlers for system generated events. As in: actions completed with errror, trigger an event. The developer can choose to register a handler via a rule for such a event or not. In the context of this issue, the event would be produced on action error. It's not far fetched to generalize even further (and that's related to https://github.com/openwhisk/openwhisk/issues/1652).

**Comment by mbehrendt** [comment] 2017-02-02 10:56
i agree there is a broader question to be addressed re try/catch.

For the specific question of 'how do i return custom http codes if my action fails', i think there is an opp for delivering a better / more fit-for-purpose UX than just offering a general mechanism for try/catch. maybe we should separate this into 2 issues vs lumping it all into one?

**Comment by rabbah** [comment] 2017-02-02 10:57
Now to the specific use case where in effect some action that fails within the sequence needs to actually set the HTTP header for the response, BUT also at the same time terminate the rest of the sequence, there are two concerns in fact: 1. If the action behaves like a web handler and responds with a json object that terminates the http connection, it will not short circuit the rest of the sequence since it produced an activation result. 2. If it returns an error to short circuit the sequence then it can't respond with the http headers etc to terminate the http request. 

Gong further while you might suggest well on error the response should match the requirements for terminating the http request (ie instead of {headers,code} it becomes {error:{headers,code}}) then the issue is that an action inside the sequence that is not really aware of the http context could not possibly do that. So what do you do?

**Comment by rabbah** [comment] 2017-02-02 10:59
@mbehrendt we do have the ability to allow actions to respond as http headers. The issue here is not that specifically. It's what happens under composition when you compose actions some of which are just "functions".

**Comment by mbehrendt** [comment] 2017-02-02 11:03
> Gong further while you might suggest well on error the response should match the requirements for terminating the http request (ie instead of {headers,code} it becomes {error:{headers,code}}) then the issue is that an action inside the sequence that is not really aware of the http context could not possibly do that.

in which sense is it not available to the action? eg the action could return a http json with 403 as the code, which would be interpreted by the controller?

**Comment by rabbah** [comment] 2017-02-02 11:08
Say you have a sequence A => B => C. Say C is a web action and can set the status etc on the http request. Now let B be an action from a public package e.g. Watson translate. If B fails it returns {error:}. As a result C does not run. If C ran then it can respond with a proper status code. But how do you get C to run when B fails? You don't have access to B's code it's in a package you don't own. Options are: That's what we started :)

**Comment by mbehrendt** [comment] 2017-02-02 11:22
well, you just changed the scenario to require the more general try/catch mechanism :-) . It's a valid one, but not the one I described and which I understood from Nick. We'll have many cases where no 3rd party action is being used, and making them as simple as possible has benefits.

**Comment by rabbah** [comment] 2017-02-02 11:36
> you just changed the scenario to require the more general try/catch mechanism

I did? That's the scenarios described by Nick in the issue description. I just made it clearer: he points out that `B` needs to short circuit the sequence (don't run C) but needs to terminate the HTTP response as well. So how do you do both things?

That I used B to mean third party action you can't modify is to exactly separate the two distinct issues.

**Comment by mbehrendt** [comment] 2017-02-02 11:40
> I did? 

yeah, I think you did by making B a 3rd party action. In a world where code of all actions is under my control, things become much easier -- so why impose the increased complexity of a world with both custom & 3rd party code on folks who are just writing actions by themselves?

**Comment by rabbah** [comment] 2017-02-02 12:05
OK - so if the developer controls all the code, how does B short circuit C from running (the semantics of a sequence is once an action returns an error, it terminates the sequence)? If it does by returning `{error: {code: 403}}` to stop C from running AND terminate the HTTP with the desired code, are you then suggesting that every action in the sequence now has to return with an appropriate error response that knows how to terminate the HTTP connection as well? Even if a developer is reusing their own code and controls all of it, there is no free lunch: either every action in the sequence must be aware that it needs to respond with an object that can terminate the HTTP request, or every action must be wrapped with another action that does the same, or some thing else. Back to where this issue started, no? Making B a black box just forces you to accept this quicker.

**Comment by mbehrendt** [comment] 2017-02-02 12:11
> either every action in the sequence (think more than 3) must be aware that it needs to respond with an object that can terminate the HTTP request

right -- is there an issue with that? As a dev writing a set of actions, which are put into a sequence, know that i'm writing this to be used in an http context or not. If i'm writing this in an http context, it would be natural to me to return http codes.

I agree there are more general purpose use cases that have to be served in a more general purpose fashion, but i think it's good objective to make the simple things simple.

**Comment by rabbah** [comment] 2017-02-02 12:23
I am concerned that it makes reusing previously developed assets harder: you can't reuse them as is. It conflates the behavior of the action with its context. It is bad for software engineering practices? Is it akin to dictating every method (action) one writes must try catch/recover vs selectively adding try catch/recover where it makes sense for the context of the composition.

The simple thing is not so simple for these reasons: it's intrusive. I'm also not stating that the proposal for recover is simple. Or the system generated events proposal is simple. I am pointing out that there are tradeoffs to each whether its on the programming model, the developer's burden, or the system's implementation.

**Comment by starpit** [comment] 2017-02-02 12:33
re: the asynchronous recovery proposal by @sjfink 

how would the 403s filter back to the client, which is expecting a response to its request? in my particular example, the client needs to redirect the user to a login back, because the user's token has expired. how can the client distinguish "failed invocation" from "maybe possibly at some point in the future, 403"?

**Comment by mbehrendt** [comment] 2017-02-02 12:34
to clarify -- i'm not suggesting an either/or. I *think* we'll need 2 approaches, one for the simple/fit-for-purpose case and one for the generic case. There is no good or bad in this, since it seems like we have 2 different, but both valid use cases. As you stated there are trade-offs.

By making 2 options available to the developer, we give him choice to pick the one that fits best his needs. If we only offered the simple or generic one, we'd either not solve the generic problem or make the simple case harder than it is, which is not desirable.

I'm not hung up on the implementation approach (ideally we can come up with a unified one) and very interested in alternative options, but only offering folks a more-complex-than-needed approach for asset reuse (even if they don't want to) is I think as bad as not allowing them to reuse assets.

**Comment by mbehrendt** [comment] 2017-02-02 12:39
adding to what I wrote above: I shouldn't have called it simple vs complex but rather sth like "code is fully under my control" vs. "I want to reuse unmodified assets"

**Comment by starpit** [comment] 2017-02-02 12:44
the tricky part of my particular example is that action `B`'s 403 failure mode has meaning that can't be lost in a more generic "oops, some action in my sequence messed up" error handler. thus, however we do this, some specific information from `B`, on token expiration, must "percolate out".

i.e.
```
A.then(B).then(C).catch(handle403)
```

doesn't quite work, because the sequence may have many failure modes, in addition to token expiration at point `B`.

how does `B` communicate this information outwards? do we just "pay the piper", and force every action to be a participant in a particular client protocol (http, in my example)? or is there some way to separate the concerns, so that `B` knows only about token expiration, and the sequence (being web-exported) handles the protocol issues...

**Comment by starpit** [comment] 2017-02-02 13:04
i think async/recoverWith is an important enough pattern that we should find some way to navigate in that direction.

we either need synchronous recovery (in my 403 example, where i'd like to consolidate the concern of 403 recovery, and not have it infect every action), or async recovery (e.g. when i want to unify my logging/notification handling, and not have it infect every single action). but, in either case, the need to consolidate handling logic, and separate failure modes from client protocol, and from the sync/async recovery mode... these seem like good goals

**Comment by jthomas** [comment] 2017-02-02 16:28
Reading the comments above, I've been thinking about how as a developer I might want to handle errors in a sequenced-define service and also extend web actions with features like authentication without having to replicate lots of boilerplate. 

If I want to expose a translation service, using the built-in watson package, I can imagine building the following sequence:

S1: A -> B -> C
A: parse HTTP event parameters and return data to translate into the expected output format.
B: built-in watson translate service
C: format translation output into expected JSON format. 

Now, what if B fails? I like the Promise based example of being able to attach a `catch()` equivalent to a sequence that handles the rejection and would be able to return the expected HTTP response for failure cases like this. 
S1: A -> B -> C
     errors   -> D

D would return` {statusCode: 403, message: "some error message"}`.

At a later point, I might want to add authentication to this service. Rather than having to manually update A to handle this (which would be replicated in every sequence), I would create a new action (E) that handles this. If authentication passes, it just returns input parameters, other it throws the rejection. 

This would allow me to define a new sequence, S2, adding auth onto my service with minimal effort. I could use this pattern for adding auth to any service. 

S2: E -> S1 

This second sequence would not have a`catch()` path defined. If E fails, it throws the error with the failure response in. If S1 fails, the result returned by D will be returned as the error response.

**Comment by michaelmarth** [comment] 2017-02-04 13:35
pretty much thought the same as @jthomas - would like to add that the approach sketched by him also works for composites other than sequences once we get to those.

**Comment by rabbah** [comment] 2017-02-04 15:57
The approached sketched by @jthomas is the same as the one for @starpit. This approach in general allows for composition. 

Nick suggested attaching the catch handlers via an annotation on the action. Another approach is to define in addition to "main", an optional catch handler as well. The latter has a nice property of colocating the handling down at the invoker level.

**Comment by sjfink** [comment] 2017-02-04 16:13
I think we could prototype this with a 'catch' combinator implemented at user-level using whisk.invoke() ,and then promote it to a full-fledged language feature after playing with with.

**Comment by starpit** [comment] 2017-02-04 20:49
if we do a user-level catch, how would we put a catch around a "native" sequence?

**Comment by starpit** [comment] 2017-02-04 21:35
@rabbah the "catch" method approach won't work for sequences, will it?

**Comment by sjfink** [comment] 2017-02-05 01:59
@starpit I'm imagining a user-level catch combinator that takes an action A (either a sequence or not) and an action C.   It invokes A via whisk.invoke.   If the result is abnormal, it invokes C via whisk.invoke and returns the result.

**Comment by rabbah** [comment] 2017-02-24 22:42
see new package/action: `/whisk.system/combinators/trycatch`

**Comment by rabbah** [comment] 2017-02-24 22:44
@starpit between the new error handling in web actions and `trycatch` as an action, can we stick a fork in this?

**Comment by rabbah** [comment] 2017-03-10 15:11
closing by silent assent.

**Closed by rabbah** 2017-03-10 15:11 UTC
Labels: programming model
