### ISSUE TITLE
wsk sdk install docker fails due to missing tarball

### ISSUE THREAD

**Issue by vmtyler** [openwhisk/openwhisk#74] opened 2016-03-14 13:01 UTC
the command
`wsk sdk install docker`
looks for the tarball on the API host. it's not being hosted by the API endpoint and the command fails.

**Comment by perryibm** [comment] 2016-03-16 18:14
There is a related bug in that the CLI itself is also not hosted at the API host.  There are some gaps in both the build and deployment scripts caused by a conflation of developer vs user role.  The first step is to make the dockerSkeleton tar ball available in the directory structure after a build and we should have this done soon.  The second step is to make sure both tar balls (CLI and docker skeleton) which may be delayed until our migration to a new build/deploy system is done.

**Comment by sjfink** [comment] 2016-05-18 18:28
@perryibm is there any status update on this?

**Comment by perryibm** [comment] 2016-05-18 19:11
@csantanapr is in process of moving this to open.

**Comment by csantanapr** [comment] 2016-05-18 19:31
@perryibm I opened issue #441, the issue is in backlog no takers yet
Based on your https://github.com/openwhisk/openwhisk/issues/74#issuecomment-197465057
- What's the work remaining? 
- Is there work for the current CLI or the new go CLI #415?
If the only work remaining is moving the dockerSkeleton to open, then I will close #441 as a duplicate of this one since @vmtyler opened this one first, and he can get notified when this issue get's resolve.

**Comment by perryibm** [comment] 2016-05-18 20:20
I think #441 is a duplicate.  Basically, moving dockerSkeleton to open involves actually moving the directory over and making adjustments to the following:

1. Build process (scripts and directory) which used to be in ant but now is in gradle
2. One test that downloads the skeleton may need adjustment
3. The CLI will have to be adjusted based on details from step 1

**Comment by csantanapr** [comment] 2016-05-18 20:41
@perryibm Sounds good I closed dup #441 
I think the CLI change is minor and can be done in the current python CLI, if the work wants to get implemented currently.

I moved this issue from IceBox(Low) to the Backlog pipeline
Do you have intention to work on this? It's currently assigned to you.

**Comment by perryibm** [comment] 2016-05-18 20:43
I have some higher priority things to take care of.  If you would like to take a crack at it, by all means take it.

**Comment by csantanapr** [comment] 2016-05-18 20:46
yep, I understand I will leave unassigned and free for anyone to take it, even you 😄 
At this moment we are book also on higher priorities, but having unassigned it's good so it tells people it's ups for grabs

**Comment by daisy-ycguo** [comment] 2016-05-25 09:09
I have interests to fix issue. Please let me know if my understanding is correct.

The goal is to make dockerSkeleton tar ball available here: https://<apihost>/blackbox-0.1.0.tar.gz, then command `wsk sdk install docker` can download dockerSkeleton and works.

The artifacts in bluewhisk related with dockerSkeleton include:
blue/catalog/demo/dockerSkeleton
blue/tools/build.xml
blue/tools/cli/publishArtifact.sh

My plan is to create a folder in OpenWhisk: tools/blackbox, and put all related artifacts there. It may take me several days to work on it, learning by doing. If you think it's OK, I can take this issue.

**Comment by csantanapr** [comment] 2016-05-25 11:00
@daisy-ycguo I'm OK if you want to work on this. 
But we are trying move catalog content out to individual repositories. 

I will create a new repository "openwhisk-sdk-docker" 
Don't know if that will be the final name but we can use it for initial implementation 

Think about what would be the other things todo
- main README 
  - how to run tests
  - how to contribute doc
- unit tests 
- Travis and any othe continues integrations aspects
- Updste this repo to depend on the new repo

**Comment by csantanapr** [comment] 2016-05-25 13:40
@daisy-ycguo I created the repo [openwhisk/openwhisk-sdk-docker](https://github.com/openwhisk/openwhisk-sdk-docker)
Let's work together on this to populate with initial content

**Comment by csantanapr** [comment] 2016-06-21 03:37
@vmtyler This should be fix now, give it a try

**Closed by csantanapr** 2016-06-21 03:37 UTC
Labels: CLI, docker, priority:high, priority:medium, SDK
