### ISSUE TITLE
missing fields in 'wsk action get' 

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk#1875] opened 2017-02-20 11:40 UTC
For nodejs zip actions, the output of 'wsk action get' is missing 'main' and 'binary' fields (which are required for programmatic introspection of actions).

**Comment by rabbah** [comment] 2017-02-20 12:44
Duplicate of https://github.com/openwhisk/openwhisk/issues/1489 @dubeejw?

**Comment by dubeejw** [comment] 2017-02-20 15:16
@rabbah, definitely a dupe.

**Comment by rabbah** [comment] 2017-02-20 15:20
closing as duplicate then.

**Closed by rabbah** 2017-02-20 15:20 UTC
Labels: cli
