### ISSUE TITLE
Not receiving Cloudant change feed information when using the Cloudant dashboard

### ISSUE THREAD

**Issue by kolien** [openwhisk/openwhisk#81] opened 2016-03-16 13:38 UTC
Using the documentation in the README, I have tried to create a trigger associated to the change feed for a Cloudant service and looking at the `wsk activation poll`. 

The change feed does not seems to be active when using the Cloudant dashboard, when I:
1. Create a database (corresponding to the name of the trigger parameter `dbname`.)
2. Creating a document.
3. Deleting a document.
4. Changing or cloning a document.

Note that I have successfully received change feed information when (from the terminal)
1. Invoke read and write actions for the same Cloudant service (`ask action invoke ...`).

Is this intentional (by design)?

**Comment by rabbah** [comment] 2016-03-17 00:56
How recent is your checkout if you're using OpenWhisk (and not Bluemix). I fixed a bug related to this a few days ago.

**Comment by kolien** [comment] 2016-03-17 11:20
`wsk -v package list`gives me: 
'clibuild': '2016-03-03T09:55:47-06:00'
'apiversion': 'v1'

**Comment by kolien** [comment] 2016-03-17 13:45
As additional information: 
I downloaded the wsk binary from [https://new-console.ng.bluemix.net/openwhisk/cli](url) that points to a file named "openwhisk-0.1.0.tar". This file name hasn't changed since my last install so I guess either this file does not contain the latest version or the name has not changed.

**Comment by paulcastro** [comment] 2016-03-17 14:47
@kolien, this order works for me:

1. create DB in Cloudant
2. create trigger on Cloudant changes feed per README.

I don't receive updates if I reverse the order and create the trigger before the DB exists.

**Comment by kolien** [comment] 2016-03-17 14:52
Thanks for clearing that up for me. I did not try that. Maybe the readme should be updated with a information that the database has to be created first.

**Comment by paulcastro** [comment] 2016-03-17 14:54
Yes.  Perhaps return an error if the feed cannot be setup successfully.

**Comment by kolien** [comment] 2016-03-18 11:05
I did a new test today.

1. Downloaded openwhisk CLI using pip.
2. Deleting old trigger.
3. Created a new trigger towards the same cloudant service that now already contains a testdb database. 
4. Starting activation poll
5. invoking read/write actions using CLI, receiving change related messages in activation poll as expected 
6. Manually creating docs and changing docs using cloudant dashboard, activation poll now does not reflect these changes (i.e. no updates in the changes logs)

My initial statement that "activation poll does not receive change information via the trigger" is still is valid. 

@paulcastro: I cannot get the same result as you. How do you perform your test?

**Comment by paulcastro** [comment] 2016-03-18 14:53
@kolien , I performed the same steps as you and I'm able to get change notifications using the CLI as well as the Cloudant Dashboard.  My current setup follows the "Setting up a Cloudant database outside Bluemix"

**Comment by kolien** [comment] 2016-03-19 10:10
@paulcastro, I followed the "Setting up a Cloudant database in Bluemix" recipe.

**Comment by paulcastro** [comment] 2016-03-19 14:12
@kolien , I changed my setup to use the Cloudant database in Bluemix and I'm able to replicate this issue.  I only see changes when the write is issued from the CLI.  I am unable to see changes when I use the Cloudant dashboard.  @rabbah I suppose this is a bug -- perhaps because Bluemix setups have to go thru the Bluemix Cloudant broker?

If you would like to use the Cloudant dashboard, I recommend setting up the Cloudant database outside of Bluemix as a workaround. That works for me.

Thanks for finding this!

**Comment by rabbah** [comment] 2016-03-19 14:34
This defect was addressed in the above mentioned commit but is not yet deployed to Bluemix. I will post an update when it's available.

**Comment by rabbah** [comment] 2016-04-07 00:25
This fix was deployed to Bluemix but I forgot to update the issue. I have confirmed the trigger activations now appear in the `wsk activation poll`.

**Closed** 2016-04-07 00:25 UTC
