### ISSUE TITLE
web-exported actions return "requires authentication" when passed invalid json

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk#1904] opened 2017-02-24 13:36 UTC
try curl'ing to a web-exported action, passing it invalid JSON (e.g. a missing quote somewhere), and you'll get back "The resource requires authentication, which was not supplied with the request", which is a pretty misleading error message.

**Comment by rabbah** [comment] 2017-02-24 13:41
Duplicate of https://github.com/openwhisk/openwhisk/issues/1886.

**Closed by rabbah** 2017-02-24 13:41 UTC
