### ISSUE TITLE
cli help shows invalid default of -1 in help information for action limits

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#1358] opened 2016-10-01 01:13 UTC
```
wsk action update -h
  -t, --timeout LIMIT 
         the timeout LIMIT in milliseconds when the action will be terminated (default -1)
  -l, --logsize LIMIT
          the log size LIMIT in MB of the container that runs the action (default 10MB) (default -1)
  -m, --memory LIMIT  
         the memory LIMIT in MB of the container that runs the action (default -1)
```

what is `-1`? That is not a valid value for any of these limits.

**Comment by dubeejw** [comment] 2016-10-06 13:20
What is the default memory limit? I believe the default timeout should be 60000ms, and log size default is 10mb.

**Comment by dubeejw** [comment] 2016-10-06 13:47
Never mind, I see the default memory is 256.

**Comment by dubeejw** [comment] 2016-10-06 15:47
This is a duplicate of https://github.com/openwhisk/openwhisk/issues/1172

**Closed** 2016-10-06 15:47 UTC
Labels: bug, cli
