### ISSUE TITLE
Inconsistent error messages for entity names with illegal characters

### ISSUE THREAD

**Issue by mdeuser** [openwhisk/openwhisk#916] opened 2016-07-18 20:28 UTC
## Environment details:
- local deployment, Windows, Bluemix  
## Steps to reproduce the issue:
1.   `wsk rule create bad+rulename bad+trigname bad+actionname`
2.   Note error message
3.   `wsk rule create goodname bad+trigname bad+actionname`
4.   Note error message
## Provide the expected results and outputs:

Step 2

```
Step 2.  `...name 'bad+name' contains illegal characters`
```

Step 4

```
Step 4.  `...name 'bad+trigname' contains illegal characters
```
## Provide the actual results and outputs:

Step 4.

```
The request content was malformed:
entity name malformed
```

These error messages come from the Whisk server and are not generated by the wsk CLI.  It's unclear what entity name was malformed as this command requires several names.

**Comment by rabbah** [comment] 2016-07-18 20:59
Related to https://github.com/openwhisk/openwhisk/issues/239.

**Comment by kurtismgit** [comment] 2016-08-19 04:45
I'm hitting the same error if I try to create a rule where the action is in a package.

$wsk rule create --enable nlcTrainingRule nlcTrainingTrigger cloudbot/nlcTrainer
error: The request content was malformed:
entity name malformed (code 1015467)

I'm able to create the rule if the action is not in a package.

**Comment by mdeuser** [comment] 2016-08-19 12:45
@kurtismgit Refer to #239 which describes your issue exactly.

**Comment by rabbah** [comment] 2016-11-19 14:58
Closing as duplicate of #239.

**Closed by rabbah** 2016-11-19 14:58 UTC
Labels: controller
