### ISSUE TITLE
CLI feature request: flag for just displaying the REST api call corresponding to the command

### ISSUE THREAD

**Issue by ioana-blue** [openwhisk/openwhisk#1392] opened 2016-10-12 15:56 UTC
This is a feature request. I'd like to be able to execute a cli command in a mode in which the corresponding REST api call(s) are printed without actually executing the calls. 

Not sure there is such a flag for the `wsk` cli, couldn't find one.

**Comment by rabbah** [comment] 2016-10-12 16:27
Duplicate of #350.

**Closed by rabbah** 2016-10-12 16:27 UTC
Labels: cli, enhancement
