### ISSUE TITLE
wsk activation poll doesn't show anything after a trigger was created

### ISSUE THREAD

**Issue by nheidloff** [openwhisk/openwhisk#92] opened 2016-03-18 07:20 UTC
The documentation https://new-console.ng.bluemix.net/docs/openwhisk/openwhisk_catalog.html#openwhisk_catalog_cloudant states in section "Listening for changes to a Cloudant database" that wsk activation poll should show when the trigger is executed. 

But this only works after a rule has been created that includes that same trigger and an action.

Could the documentation be updated? Or even better log something when the trigger is executed.

**Comment by kolien** [comment] 2016-03-18 10:04
I have noted a similar somewhat related behavior, that activation poll only registers information when "read" and "write" actions are invoked, but not when database content is changed or created using the Cloudant Dashboard (inside Bluemix)

**Comment by rabbah** [comment] 2016-03-19 15:15
This is a duplicate of #81.

**Closed by rabbah** 2016-03-19 15:15 UTC
