### ISSUE TITLE
wsk activation list should show timestamp of activation (even in a human readable format)

### ISSUE THREAD

**Issue by nauerz-ibm** [openwhisk/openwhisk#313] opened 2016-05-04 09:22 UTC
wsk activation list should show timestamp of activation (even in a human readable format).
Not sure if this is a dup; if so, please close.

**Comment by rabbah** [comment] 2016-05-04 09:36
You mean `wsk activation list` - Why should a rule list show activations otherwise?

**Comment by nauerz-ibm** [comment] 2016-05-04 09:38
@rabbah Sorry, yes, copy & paste error :)

**Comment by rabbah** [comment] 2016-05-04 09:47
Duplicate of #279 and #20.

**Closed by rabbah** 2016-05-04 09:47 UTC
Labels: CLI, enhancement
