### ISSUE TITLE
Enhance API to query the runtimes available

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#619] opened 2016-06-10 15:52 UTC
This is related to #618 

We support the --kind for action to specify the runtime version like nodejs:6 

As we add more runtimes we could have multiple nodejs versions (i.e. 6.2.1, 6.3.4, 7.0.1, etc..)

After implementing #618 

It will be useful to have a client API to query the available runtimes versions for all languages 
It can be part of the object already return in /v1/info or a new API /v1/info/runtimes

Related to #547

This will allow client side libraries or tools (client-js, CLI) to query runtime kinds and present to the user.

cc @sjfink @jasonpet

**Comment by markusthoemmes** [comment] 2016-06-10 19:35
+1 on including it in `/api/v1`. Or go super fancy: Include it in `OPTIONS /api/v1/namespaces/_/actions`

**Comment by csantanapr** [comment] 2016-06-10 20:28
>+1 on including it in /api/v1. Or go super fancy: Include it in OPTIONS /api/v1/namespaces/_/actions

I'm fine with either as long whiskswagger.json get's updated 😹

**Comment by markusthoemmes** [comment] 2016-06-13 21:26
This is actually related to #335 which goes a step further and also enumerates limits. Close this as dup? @csantanapr

**Comment by csantanapr** [comment] 2016-06-14 10:30
@markusthoemmes yes we can close as dup as long we copy the requirements and add them to #335

**Comment by rabbah** [comment] 2017-03-07 23:11
closing as duplicate of #335.

**Closed by rabbah** 2017-03-07 23:11 UTC
Labels: API
