### ISSUE TITLE
Swift action parsing doesn't tolerate special characters

### ISSUE THREAD

**Issue by bjustin-ibm** [openwhisk/openwhisk#362] opened 2016-05-09 14:34 UTC
For example, if I try to run an action with the following code:

``` swift
//  Copyright © 2016 Dirk Beanberger. All rights reserved.
func main(args: [String:Any]) -> [String:Any] {
  return ["message": "This should just work..."]
}
```

I always get an error of `the action did not produce a valid JSON response`

However, if I simply remove the `©` everything works as expected.

**Comment by rabbah** [comment] 2016-05-09 14:36
This may not be specific to Swift - see #252.

**Comment by bjustin-ibm** [comment] 2016-05-09 14:43
@rabbah That seems pretty likely. The Swift action file handling already is explicit about using UTF-8. I suggest keeping this open to verify that #252 actually fixes this specific symptom.

**Comment by rabbah** [comment] 2016-05-09 15:01
Your symptom is different - `the action did not produce a valid JSON response` suggests there was a failure executing the action (I would check the proxy for example to confirm it returned the correct value). The defect from 252 will manifest differently (the activation record will show a different result value).

**Comment by rabbah** [comment] 2017-01-06 14:52
@bjustin-ibm @paulcastro is this still valid?

**Comment by bjustin-ibm** [comment] 2017-01-06 15:02
@rabbah It is still valid. On the Swift 3 runtime, I get the following error, but only with the copyright character present:

```
{
  "error": "The action failed to generate or locate a binary. See logs for details."
}
```

**Comment by paulcastro** [comment] 2017-01-09 21:10
@bjustin-ibm that message indicates a compilation error.

**Comment by stevenatkin** [comment] 2017-01-24 16:33
I believe that this is tied to #252. We really need to get someone to take a look at this. I don't think that this should be too hard to fix. I think the problem is that they are running OpenWhisk in the wrong codepage they should be running in UTF-8. My guess is that they are probably defaulting to ISO8859-1 (Latin 1) when they should be using Unicode.

**Comment by rabbah** [comment] 2017-01-25 02:04
The fix for #252 is necessary but not sufficient to fix swift (and python) actions. The proxy needs to handle utf-8 encoding, where it currently does not; pr #1757 includes the required invoker side fix.

**Comment by rabbah** [comment] 2017-01-25 03:52
proposed patch https://github.com/openwhisk/openwhisk/pull/1757/commits/95c34333210348f0af44a0ece0d44efc4412a688.

**Comment by rabbah** [comment] 2017-01-25 18:46
Fix merged via #1757. Leaving open however to investigate Travis failure via CLI tests of new unicode python/swift actions.

**Comment by cclauss** [comment] 2017-03-14 22:15
Is this still in progress?

**Comment by rabbah** [comment] 2017-03-14 23:57
The Travis issue might still exist. I have not investigated.

**Comment by rabbah** [comment] 2017-03-25 23:15
Looks like we have a recent regression in the swift actions.

**Comment by rabbah** [comment] 2017-03-27 14:28
tests enabled in pr #2070.

**Closed** 2017-04-03 18:03 UTC
Labels: python, runtime, swift
