### ISSUE TITLE
[CLI] "package refresh" seems not work?

### ISSUE THREAD

**Issue by archerzz** [openwhisk/openwhisk#1366] opened 2016-10-05 15:09 UTC
## Environment details:

**Irrelevant**
## Steps to reproduce the issue:
1.   Execute "wsk package refresh NAMESPACE"
## Provide the expected results and outputs:

```
There should be messages regarding successful package refreshing.
```
## Provide the actual results and outputs:

```
Error message is returned:
Request failure: Malformed request, did you specify a bluemix namespace?
```
## Additional information you deem important:
- It seems a backend REST API issue. I checked the HTTP transaction, the request should be fine. There is namespace in the URL path.

``` bash
REQUEST:
[POST]  https://openwhisk.ng.bluemix.net/api/v1/namespaces/XX_YY/packages/refresh
Req Headers
{
  "Authorization": [
    "Basic XXXXXXX"
  ]
}RESPONSE:Got response with code 400
Response body size is 67 bytes
Response body received:
{"error":"Malformed request, did you specify a bluemix namespace?"}
```

**Comment by markusthoemmes** [comment] 2016-10-05 15:11
Hi @archerzz, thanks for raising this issue.

Do you have a second `_` in either your Organization and/or Space name? If so, duplicate of #91 .

**Comment by archerzz** [comment] 2016-10-20 13:08
Sorry for the delay. Yes. There are multiple "_". Please close is as duplicated. Thanks.

**Closed** 2017-01-12 11:50 UTC
Labels: API, cli
