### ISSUE TITLE
CLI should create sequences with the annotation isSequence

### ISSUE THREAD

**Issue by eweiter** [openwhisk/openwhisk#1485] opened 2016-11-08 20:28 UTC
The CLI should create sequences with the annotation "isSequence".  The whisk backend has recently started using "kind: sequence" for sequences, but the API endpoint calls to get all entities or get all actions does not return the "exec" object that contains this "kind" attribute. 

In order to find out if an action is a sequence a subsequent GET call has to be made to fetch this additional information.  If there is a list of actions that this is needed for then each of those actions will need the additional GET call performed and the performance costs of this can be very costly.

The CLI should be able to pass along a similar payload when it creates a sequence:
![image](https://cloud.githubusercontent.com/assets/19595703/20115837/d1b9e804-a5c7-11e6-8428-e3c38d1b36e5.png)

**Comment by dubeejw** [comment] 2016-11-11 16:25
@eweiter, @rabbah, I'm not sure we should be relying on annotations to read valuable data from. It seems like it would make more sense to update the API endpoint to return a field in the exec JSON object that denotes that an action is a sequence.

**Comment by dubeejw** [comment] 2016-11-11 16:43
As an example:

```
{
  "name": "sequenceAction1",
  "sequence": true,
  "publish": false,
  "annotations": [],
  "version": "0.0.1",
  "namespace": "_"
}, {
  "name": "nonSequenceAction",
  "publish": false,
  "annotations": [],
  "version": "0.0.1",
  "namespace": "_"
}
```

**Comment by rabbah** [comment] 2016-11-11 17:00
@dubeejw the type of the `exec` is of course available in the action - the requested change is related to doing a `list` operation on actions which constructs a view of the actions in one's namespace. We can extract the kind from the exec and construct a new view but this results in a schema change. We will avoid this by adding the information to the annotation instead.

I'll take this one, it's a small and quick change.

**Comment by eweiter** [comment] 2016-11-11 17:00
@dubeejw 
So there is an issue already open that would address that, Issue #427 .
So I guess we can close this issue and wait for the other to finish

**Comment by eweiter** [comment] 2016-11-11 17:02
@rabbah @dubeejw 
So are we just going to do this change instead of #427 since it is quicker? Either way will alleviate the issue for the UI.

**Comment by rabbah** [comment] 2016-11-11 17:02
closing as duplicate of #427.

**Closed by rabbah** 2016-11-11 17:02 UTC
