### ISSUE TITLE
Copy ${nginx.scratch}/nginx/nginx.conf to ${nginx.conf.dir}/nginx.conf failed because of "Permission denied"

### ISSUE THREAD

**Issue by daisy-ycguo** [openwhisk/openwhisk#700] opened 2016-06-20 09:39 UTC
Hi,

I tried to install the lasted OpenWhisk today, but I met with following error.

buildProxy:
    [mkdir] Created dir: /home/daisy/workspace/openwhisk/build/docker-scratch/nginx501240774/nginx
     [copy] Copying 1 file to /tmp/nginx

BUILD FAILED
/home/daisy/workspace/openwhisk/build.xml:41: The following error occurred while executing this line:
/home/daisy/workspace/openwhisk/services/nginx/build.xml:23: Failed to copy /home/daisy/workspace/openwhisk/build/docker-scratch/nginx501240774/nginx/nginx.conf to /tmp/nginx/nginx.conf due to java.io.FileNotFoundException /tmp/nginx/nginx.conf (Permission denied)

I checked the permission of /tmp/nginx/nginx.conf. The owner is root.
`drwxr-xr-x  2 root  root  4096  6月 19 22:02 nginx`

I think it is because the folder /tmp/nginx was created and mounted by docker. I don't know if there is a way to resolve this issue excepting running `ant build` with root. Or do we require root permission to run `ant build` ? If it's true, we shall document it.

Daisy

**Comment by rabbah** [comment] 2016-06-20 09:43
Duplicate of #32.

**Closed** 2016-06-20 09:45 UTC
