### ISSUE TITLE
Documentation for the Alarms package

### ISSUE THREAD

**Issue by ioana-blue** [openwhisk/openwhisk#278] opened 2016-04-28 20:22 UTC
The documentation for the Alarms package seems incomplete and somewhat non-intuitive. 

To find some information about the package, one can type:
```
wsk package get --summary /whisk.system/alarms
```

Some information follows (indentation seems off):
```
package /whisk.system/alarms: Alarms and periodic utility
   (params: cron trigger_payload)
 feed   /whisk.system/alarms/alarm: Fire trigger when alarm occurs
```

To find more information about the alarm feed, I would expect to type:
```
wsk feed get --summary /whisk.system/alarms/alarm
```
 which doesn't seem to work. Replacing `feed` with  `action` seems to produce some information, but it seems incomplete (no mention of the # of fires, which I think is one of the parameters). 

On a slightly related note, in the output for `./wsk action get --help`, I would replace `project` with `property` since projection is what happens as a consequence of providing the property.

**Comment by csantanapr** [comment] 2016-08-09 23:45
Closing as duplicate of #575 to address `wsk feed` in CLI

For `wsk action get --help` new go-CLI takes cares of this
```
 $ ./bin/go-cli/wsk action get --help
get action
Usage:
  wsk action get <name string> [flags]

Flags:
  -s, --summary   summarize entity details

Global Flags:
      --apihost string      whisk API host
      --apiversion string   whisk API version
  -u, --auth string         authorization key
  -d, --debug               debug level output
  -i, --insecure            bypass certificate checking
  -v, --verbose             verbose output
```

**Closed by csantanapr** 2016-08-09 23:45 UTC
Labels: documentation, enhancement
