### ISSUE TITLE
Fancy UTF characters in NodeJS action code lead to parsing error

### ISSUE THREAD

**Issue by l2fprod** [openwhisk/openwhisk#1516] opened 2016-11-16 13:46 UTC
I came across this issue as I was trying to use the "geolib" library bundled with webpack. The geolib library uses some fancy variable names https://github.com/manuelbieh/Geolib/blob/master/src/geolib.js#L1110
```
var δ = Number(distance) / radius; // angular distance in radians
var θ = Number(bearing).toRad();
```
and when bundled into the webpack (which I don't obfuscate for now), I'm getting a parsing error when invoking the action.

It can be reproduced with:
```
function main(args) {
  var δ = 3;
  whisk.done({});
}
```

Create and invoke this action leads to a parsing error:
```
Activation: bug (37dba1e3dbf34dff8e932a7b5bbd2d61)
[
    "2016-11-16T13:37:46.237630784Z stderr: Error during initialization: SyntaxError: Unexpected token ?",
    "2016-11-16T13:37:46.237646349Z stderr: at NodeActionRunner.init (/nodejsAction/runner.js:79:29)",
    "2016-11-16T13:37:46.237653949Z stderr: at doInit (/nodejsAction/src/service.js:134:31)",
    "2016-11-16T13:37:46.237660911Z stderr: at initCode (/nodejsAction/src/service.js:80:24)",
    "2016-11-16T13:37:46.237667995Z stderr: at /nodejsAction/app.js:62:13",
    "2016-11-16T13:37:46.237675457Z stderr: at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:95:5)",
    "2016-11-16T13:37:46.237684586Z stderr: at next (/nodejsAction/node_modules/express/lib/router/route.js:131:13)",
    "2016-11-16T13:37:46.237691999Z stderr: at Route.dispatch (/nodejsAction/node_modules/express/lib/router/route.js:112:3)",
    "2016-11-16T13:37:46.237699189Z stderr: at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:95:5)",
    "2016-11-16T13:37:46.237706317Z stderr: at /nodejsAction/node_modules/express/lib/router/index.js:277:22",
    "2016-11-16T13:37:46.237713283Z stderr: at Function.process_params (/nodejsAction/node_modules/express/lib/router/index.js:330:12)"
```

The action exec.code looks correct so maybe the encoding is lost somewhere between there and its invocation:
```
fred@flavigne ~/dev/logistics/logistics-wizard-recommendation> wsk action get bug
ok: got action bug
{
    "namespace": "*******",
    "name": "bug",
    "version": "0.0.23",
    "publish": false,
    "exec": {
        "kind": "nodejs:6",
        "code": "function main(args) {\n  var δ = 3;\n  whisk.done({});\n}\n"
    },
    "limits": {
        "timeout": 60000,
        "memory": 256,
        "logs": 10
    }
}
```

If you run the .js directly node does not complain, even if loaded via "eval".

**Comment by rabbah** [comment] 2016-11-16 14:02
This may be related to https://github.com/openwhisk/openwhisk/issues/252.

**Comment by rabbah** [comment] 2017-01-24 22:49
Confirmed duplicate of #252.

**Closed by rabbah** 2017-01-24 22:49 UTC
