### ISSUE TITLE
Update REST API to contain Various Activity Transaction Time

### ISSUE THREAD

**Issue by johnsolm** [openwhisk/openwhisk#382] opened 2016-05-11 16:44 UTC
## Calculate and Store Activity Transaction Time

As a user of Whisk I would like to be able to be able to understand how much time is spent performing various Whisk Activities.  I need to know more than just the overall execution time.  Here are the sorts of details I would like to know:

1) **user**: billable time in the action

2) **system**:  controller-to-controller time - user

3) **network**: time to communicate from user’s browser to CF Node.js web application that implements the REST Client **

4) **REST Client**:  user-measured client-to-server response time - user - system - network **

<img width="605" alt="screen shot 2016-05-11 at 12 42 49 pm" src="https://cloud.githubusercontent.com/assets/19310654/15188882/f820f66c-1775-11e6-9663-f5f3d68e6c94.png">

*\* I would like to know the **ui** and **network** times for the following two reasons:
1. performance testing
2. to avoid confusion between the amount of time I witness the browser (or other REST client) take and the amount of time portrayed by the **user** and **system** times.

**As a result, the backend REST API should be updated to include 4 new parameters:**
1. user (as defined as above)
2. system (as defined as above)
3. network - which is the time it takes to communicate from the REST Client to the the API Server. 
4. REST Client - (as defined above)

**Note:** For now we could avoid displaying 3 and 4 on the Whisk UI.

**Comment by rabbah** [comment] 2017-01-06 14:53
Going to close this as a duplicate of https://github.com/openwhisk/openwhisk/issues/373 (since by way of creating transient records, we can record the various checkpoints).

**Closed by rabbah** 2017-01-06 14:53 UTC
Labels: API
