### ISSUE TITLE
Can't create package action with 22MB zip Erro: request entity too large

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#1543] opened 2016-11-21 19:01 UTC
Steps to reproduce:
```
$ node -v
v6.7.0
$ npm -v
3.10.3
npm init -y
npm install watson-developer-cloud --save
zip -r action.zip *
-rw-r--r--  1 csantanapr  staff    22M Nov 21 13:42 action.zip
wsk -v action create packageAction --kind nodejs:6 action.zip
```

Error Output:
```
RESPONSE:Got response with code 413
Response body size is 59 bytes
Response body received:
{
  "error": "request entity too large",
  "code": 523257
}
error: Unable to create action: request entity too large (code 523257)
```

**Comment by psuter** [comment] 2016-12-07 18:07
Trying the steps above gives me a larger action. I suspect versions/dependencies may have changed:

    $ du -h action.zip
     42M    action.zip
    $ base64 action.zip | wc
       1       1 59079765

So the base64-encoded version is over 50M, and it hits the nginx limit (currently set to 50M). The request never even makes it to the controller.

Will try an action around 22M.

**Comment by psuter** [comment] 2016-12-07 18:17
These steps seem to reproduce the issue without depending on `npm` versions:

    $ base64 /dev/urandom | head -c 28000000 > 28M.txt                                                         
    $ zip action.zip 28M.txt 
    adding: 29M.txt (deflated 24%)
    $ du -h action.zip 
     20M    action.zip
    $ wsk action create bigzip action.zip --kind nodejs:6
    error: Unable to create action: request entity too large (code 93)

**Comment by psuter** [comment] 2016-12-07 19:09
The issue is that the controller measures the size of strings as the memory they use on the heap, while the natural expectation is to measure their bytesize in UTF8.

**Comment by rabbah** [comment] 2016-12-14 18:20
Fixed with https://github.com/openwhisk/openwhisk/commit/d191985b67130f58766131c9fa56d05237f83fbf.

**Closed by rabbah** 2016-12-14 18:20 UTC
Labels: API

**Comment by csantanapr** [comment] 2016-12-14 19:03
This is super 🎉👍🏼🙌😀✊🏻👏🏼
