### ISSUE TITLE
Persistent couchdb will fail in "ant deploy"

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk#595] opened 2016-06-08 02:34 UTC
If we are still using ant commands to build the whisk, persistent couchdb will fail at ant deploy with the following errors, while the default ephemeral couchdb works OK:
```
installCatalog:
     [exec] Installing open catalog
     [exec] Installing package installSystem.sh with pid 8549
     [exec] Installing package installGit.sh with pid 8550
     [exec] Installing package installSlack.sh with pid 8551
     [exec] Installing package installWatson.sh with pid 8552
     [exec] Installing package installWeather.sh with pid 8553
     [exec] Installing Slack package.
     [exec] Creating package slack with pid 8589
     [exec] Installing Git package.
     [exec] Creating package github with pid 8592
     [exec] Installing whisk.system entities.
     [exec] Creating package system with pid 8601
     [exec] Creating package util with pid 8602
     [exec] Creating package samples with pid 8603
     [exec] Installing Watson package.
     [exec] Creating package watson with pid 8604
     [exec] Installing Weather package.
     [exec] Creating package weather with pid 8605
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 5)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 10)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 9)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 6)
     [exec] 8601 finished with status 247
     [exec] 8602 finished with status 247
     [exec] 8603 finished with status 247
     [exec] Installing system/pipe with pid 8606
     [exec] Installing util/cat with pid 8607
     [exec] Installing util/split with pid 8608
     [exec] Installing util/sort with pid 8609
     [exec] Installing util/head with pid 8610
     [exec] Installing util/date with pid 8611
     [exec] Installing samples/helloWorld with pid 8612
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 8)
     [exec] Installing samples/greeting with pid 8613
     [exec] Installing samples/wordCount with pid 8614
     [exec] Installing samples/echo with pid 8615
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 4)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 7)
     [exec] 8604 finished with status 247
     [exec] Installing watson/speechToText with pid 8616
     [exec] Installing watson/translate with pid 8617
     [exec] Installing watson/languageId with pid 8618
     [exec] 8589 finished with status 247
     [exec] Installing slack/post with pid 8619
     [exec] Installing watson/textToSpeech with pid 8620
     [exec] 8605 finished with status 247
     [exec] 8592 finished with status 247
     [exec] Installing weather/forecast with pid 8621
     [exec] Installing github/webhook with pid 8622
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 11)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 12)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 13)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 14)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 15)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 16)
     [exec] 8622 finished with status 247
     [exec] Git package ERRORS = 2
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 17)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 19)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 18)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 20)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 22)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 21)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 24)
     [exec] 8621 finished with status 247
     [exec] Weather package ERRORS = 2
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 25)
     [exec] 8616 finished with status 247
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 26)
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 27)
     [exec] 8619 finished with status 247
     [exec] Slack package ERRORS = 2
     [exec] error: The server is currently unavailable (because it is overloaded or down for maintenance). (code 23)
     [exec] 8606 finished with status 247
     [exec] 8607 finished with status 247
     [exec] 8608 finished with status 247
     [exec] 8609 finished with status 247
     [exec] 8610 finished with status 247
     [exec] 8611 finished with status 247
     [exec] 8612 finished with status 247
     [exec] 8613 finished with status 247
     [exec] 8614 finished with status 247
     [exec] 8615 finished with status 247
     [exec] whisk.system entities ERRORS = 13
     [exec] 8549 finished with status 13
     [exec] 8550 finished with status 2
     [exec] 8551 finished with status 2
     [exec] 8617 finished with status 247
     [exec] 8618 finished with status 247
     [exec] 8620 finished with status 247
     [exec] Watson package ERRORS = 5
     [exec] 8552 finished with status 5
     [exec] 8553 finished with status 2
     [exec] open catalog ERRORS = 5

BUILD FAILED
/home/vagrant/openwhisk/build.xml:56: The following error occurred while executing this line:
/home/vagrant/openwhisk/build.xml:100: exec returned: 5
```

**Comment by rabbah** [comment] 2016-06-08 02:45
docker ps? is your couch container up?

**Comment by houshengbo** [comment] 2016-06-08 15:01
This couchdb service is installed on the same machine, where openwhisk is installed. They can be accessed via 127.0.0.1:5984.

**Comment by houshengbo** [comment] 2016-06-08 17:35
Wow, 127.0.0.1:5984 does not work, but if I switch the IP to something else like 192.168.0.23:5984, the build and deploy processes will succeed.
I am able to create the action and call the action. However, when I tried to run "wsk action list", it showed me:

vagrant@vagrant-ubuntu-trusty-64:~$ wsk action list
error: Unexpected http response code: 500 Internal Server Error (code 57)

**Comment by rabbah** [comment] 2016-06-08 17:40
I'll take a wild guess that you didn't install the couch views correctly: See https://github.com/openwhisk/openwhisk/tree/master/tools/db#using-couchdb

   * the CouchDB instance must set `reduce_limit` on views to `false` (see [this](couchdb/createAdmin.sh#L55) for how to do this via REST)

**Comment by houshengbo** [comment] 2016-06-09 21:34
If I add a section:

[query_server_config]
reduce_limit = false

into the config /etc/couchdb/local.ini, and restart the couchdb. The issue is gone.

**Comment by mrutkows** [comment] 2016-06-09 23:52
I think it might be good to record the problem and error in the README in some "Troubleshooting" section?

**Comment by rabbah** [comment] 2016-06-27 04:46
Closing as duplicate of #423.

**Closed by rabbah** 2016-06-27 04:46 UTC

**Comment by Katiyman** [comment] 2017-05-04 09:14
I am doing a local deployement on ubuntu 16.04 using local counchdb and facing similar issue 
when I run the cmd
```
bin/wsk action invoke /whisk.system/utils/echo -p message hello --result --insecure
```
I get error
```
error: Unable to invoke action 'utils/echo': The server is currently unavailable (because it is overloaded or down for maintenance). (code 152)
```
Can you please help
