### ISSUE TITLE
activation record may appear minutes after an action is invoked

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk#1672] opened 2016-12-21 11:36 UTC
When invoking an action, an activation id is returned, but the record is not available until after the action initializes (and runs?). In case of docker actions with large images, pulling the image may take very long (minutes), and the activation record is not available for practically unbound amount of time (without any indication what exactly is going on) - potentially much longer than the specified timeout (which limits the runtime, but, perhaps, not the initialization time when the image is pulled).
It could be very useful if the activation record (with the id returned by 'wsk action invoke') was surfaced to the user immediately, to make consequent polling more straightforward/intuitive.

**Comment by rabbah** [comment] 2016-12-21 11:44
Agree - this is a duplicate of https://github.com/openwhisk/openwhisk/issues/373.

**Closed** 2016-12-21 14:27 UTC
