### ISSUE TITLE
support python actions

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#16] opened 2016-02-24 16:50 UTC
As per title.

**Comment by vmtyler** [comment] 2016-03-14 12:59
The interesting part will be handling the requirements compiling. Lambda currently punts on this and requires users to upload all the packages (compiled) as part of their code. The problem is if I'm a mac user and compile lxml, it won't run on lambda because it's Amazon Linux.  At the most basic level, having  whisk run a 'pip install' (maybe even create a virtualenv) of a requirements.txt to get/compile required actions for the user would be big. That's basically what cloud foundry does in it's python buildpack- which i see you've already looked at here (https://github.ibm.com/BlueMix-Fabric/bluewhisk/issues/1427)

**Comment by ioana-blue** [comment] 2016-05-25 14:25
I think we can close this for now. Python has been working with basic tests for a while.

**Closed by ioana-blue** 2016-05-25 14:25 UTC
Labels: programming model, python

**Comment by csantanapr** [comment] 2016-05-25 14:44
@ioana-blue Could you respond to the comment https://github.com/openwhisk/openwhisk/issues/16#issuecomment-196299872
 from @vmtyler about how "handling the requirements compiling"?

**Comment by ioana-blue** [comment] 2016-06-01 15:03
For now, our solution is similar to the javascript one. We support a series of packages. At some point, we may consider a more generalized solution similar to "build packs". @vmtyler

**Comment by firasalmanna** [comment] 2017-01-25 17:13
Hello,
Is it possible to use packaged python actions? if yes, any tutorials?

**Comment by rabbah** [comment] 2017-01-25 20:10
@firasalmanna not an official solution yet. One option is compiling the python to a native binary which you can do with `bbfreeze` or maybe `grumpy` (https://github.com/google/grumpy)`. Which packages are you looking at?

**Comment by firasalmanna** [comment] 2017-01-25 20:58
@rabbah 
I am trying to upload a project I am working on, requirements file attached. the requirements can be reduced as I am dividing my app into microservices, so each will have a subset of these requirements.
So after compiling my app into binary, how am I going to upload it? I don't think I saw this option in the docs.

[requirements.txt](https://github.com/openwhisk/openwhisk/files/730930/requirements.txt)

**Comment by rabbah** [comment] 2017-01-25 21:01
You can try the approach outlined here (once you have a binary you can create an action from it).

**Comment by csantanapr** [comment] 2017-01-26 19:09
@rabbah you meant to share this link [Understanding and using Docker actions in IBM Bluemix OpenWhisk](https://www.ibm.com/blogs/bluemix/2017/01/docker-bluemix-openwhisk) that explains how to create a zip with a binary exe so @firasalmanna can use it to create an exec with python.

**Comment by firasalmanna** [comment] 2017-02-01 00:57
Hello guys,
I am having a problem after generating an executable and pushing it to openwhisk.

1- I made and executable out of my python app, I tested it locally and then tried to create an openwhisk action from it using the steps in the blog post. When I tried to invoke it, I got the message `[Errno 2] No such file or directory`
2- I tried to create a docker image, I used `dockerskeleton` as the base image, I copied my `exec` to `action/exec`, I built the image and pushed it, then why I invoke the openwhisk action created from my image, I also received the same error `[Errno 2] No such file or directory`.

I browsed the docker image files, and I found the `exec` file in the `action` directory.
Do you have an idea what could be the problem?

**Comment by rabbah** [comment] 2017-02-01 01:17
If you can exec into the container, did you run the `/action/exec` directly to confirm it works?

**Comment by firasalmanna** [comment] 2017-02-01 11:56
No, I couldn't run it, I also got `No such file or directory`  
And after some investigation, I think that the executable I generate using `pyinstaller` is `32-bit` because `pyinstaller` generates `32-bit` executable for `python 2.7`, which I am using.

Then, I found that I can execute 32 on 64 bit if there is the dynamic loader `/lib/ld-linux.so.2`. But I couldn't find it for `alpine-linux` using `apk add`.

The only options I have now is to find a different package for `alpine` that executes 32-bit, or to try to generate a 64-bit exec again.

**Comment by csantanapr** [comment] 2017-02-01 12:13
@firasalmanna what about using the approach of using bash script exec and then from bash script and then tun setup/unit and run python script (i.e. Not compiled)

Maybe I missed that you already tried this.

**Comment by rabbah** [comment] 2017-02-01 12:34
Here's another tip following Carlos: you can use this approach with nodejs actions.

**Comment by firasalmanna** [comment] 2017-02-01 12:41
@csantanapr no I didn't try this approach. I might give it a try.

But first I am thinking if trying the approach from this link https://github.com/iainhouston/dockerPython
He is renamed his python script `test.py` to `exec`, and he put it in the action directory, and everything else is the same. He also copied all his other classes to the action directory. 
Do you think this should work?

@rabbah do you mean running my script from nodejs? or using this approach to run a nodejs app?

**Comment by rabbah** [comment] 2017-02-01 12:52
Want to reach out to us on slack.openwhisk.org and we can work through it directly?
